baseURL: "http://example.org/"
languageCode: "en-us"
title: "andre de moraes - template"
author:
    name: "Andr√© de Moraes"
    email: "amancioandre@gmail.com"

defaultContentLanguage: "en"

markup:
    tableOfContents:
        endLevel: 2
        ordered: true
        startLevel: 2
